language: go

sudo: false

go:
  - 1.6
  - 1.7

default:  
  - go build $$(go list ./... | grep -v /vendor/)

before_script:
  - go fmt ./...
  - go vet $(go list ./...)

script:
  - sh testCoverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)